name: 'start'

on:
  schedule:
    - cron: "0 4,8,12,16,20 * * *"
    - cron: "0 0 * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{secrets.TOKEN}}
    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: START
        run: cd bot && bash run.sh
