name: 'start'

on:
  schedule:
    - cron: 0 1-23 * * *
    - cron: 0 0 * * *

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: START
        run: bash <(curl https://raw.githubusercontent.com/radcool510/majora-mask-bot/main/bot/run.sh) ${{secrets.TOKEN}}
